# Commented boards should be supported, but currently are not

# Rover Apps
arm:
  - arm

gamepad:
  - gamepad

gimbal:
  - gimbal

pdb:
  - pdb

science:
  - science

# Test Apps
test-aeat-6012:
  - nucleo

test-aeat-8800:
  - nucleo

test-actuator-controller:
  - nucleo
  - arm
  - gimbal
  - science

test-blinky:
  - nucleo
  - arm
  - gamepad
  - gimbal
  - pdb
  - science

test-blockingneo:
  - nucleo

test-can:
  - nucleo
  - arm
  - gimbal
#  - science

test-mae3:
  - nucleo
#  - gimbal
#  - science

test-logger:
  - gimbal
  - nucleo
  - pdb
  - science

test-lookup-table:
  - nucleo

test-adafruitSTEMMA:
#  - nucleo
  - science

test-pid:
  - nucleo
#  - arm
#  - gimbal
#  - science

test-pwm:
  - nucleo
  - arm
  - gimbal
  - pdb
  - science

test-pwmin:
  - nucleo
  - arm
#  - gamepad
#  - gimbal
#  - science

tutorial-servo-pot-control:
  - nucleo

tutorial-servo-can-control:
  - nucleo
