# Commented boards should be supported, but currently are not

# Rover Apps
arm:
  - ARM_REV2

gamepad:
  - GAMEPAD_REV1

gimbal:
  - GIMBAL_REV2

pdb:
  - PDB_REV2

science:
  - SCIENCE_REV2

# Test Apps
test-aeat-6012:
  - UWRT_NUCLEO

test-aeat-8800:
  - UWRT_NUCLEO

test-actuator-controller:
  - ARM_REV2
  - GIMBAL_REV2
  - SCIENCE_REV2
  - UWRT_NUCLEO

test-blinky:
  - ARM_REV2
  - GAMEPAD_REV1
  - GIMBAL_REV2
  - PDB_REV2
  - SCIENCE_REV2
  - UWRT_NUCLEO

test-blockingneo:
  - UWRT_NUCLEO

test-can:
  - ARM_REV2
  - GIMBAL_REV2
  #  - SCIENCE_REV2
  - UWRT_NUCLEO

test-mae3:
  #  - GIMBAL_REV2
  #  - SCIENCE_REV2
  - UWRT_NUCLEO

test-logger:
  - GIMBAL_REV2
  - PDB_REV2
  - SCIENCE_REV2
  - UWRT_NUCLEO

test-lookup-table:
  - UWRT_NUCLEO

test-adafruitSTEMMA:
  - SCIENCE_REV2
  #  - UWRT_NUCLEO

test-units:
  - UWRT_NUCLEO

test-pid:
  #  - ARM_REV2
  #  - GIMBAL_REV2
  #  - SCIENCE_REV2
  - UWRT_NUCLEO

test-pwm:
  - ARM_REV2
  - GIMBAL_REV2
  - PDB_REV2
  - SCIENCE_REV2
  - UWRT_NUCLEO

test-pwmin:
  - ARM_REV2
  #  - GAMEPAD_REV1
  #  - GIMBAL_REV2
  #  - SCIENCE_REV2
  - UWRT_NUCLEO


test-quadrature64cpr:
  - UWRT_NUCLEO

test-watchdog:
  - UWRT_NUCLEO
