# Commented boards should be supported, but currently are not

# Rover Apps
arm:
  - arm

gamepad:
  - gamepad

gimbtonomy:
  - gimbtonomy

pdb:
  - pdb

science:
  - science

# Test Apps
test-aeat-8800:
  - nucleo

test-actuator-controller:
  - nucleo
  - arm
  - gimbtonomy
  - science

test-blinky:
  - nucleo
  - arm
  - gamepad
  - gimbtonomy
  - science

test-blockingneo:
#  - nucleo
  - gimbtonomy

test-can:
  - nucleo
  - arm
  - gimbtonomy
#  - science

test-enc-abs-pwm:
  #  - nucleo
  - arm
#  - gimbtonomy
#  - science

test-lookup-table:
  - nucleo

test-moisture:
  #  - nucleo
  - science

test-pid:
  - nucleo
#  - arm
#  - gimbtonomy
#  - science

test-pwm:
  - nucleo
  - arm
  - gimbtonomy
  - science

test-pwmin:
  #  - nucleo
  - arm
#  - gamepad
#  - gimbtonomy
#  - science
