# Rover Apps
arm:
  - arm

gimbtonomy:
  - gimbtonomy

safety:
  - safety

science:
  - science

# Test Apps
test-aeat-8800:
  - nucleo

test-actuator-controller:
  - nucleo
  - arm
  - gimbtonomy
  - science

test-blinky:
  - nucleo
  - arm
  - gimbtonomy
  - safety
  - science

test-blockingneo:
  - nucleo
  - gimbtonomy

test-can:
  - nucleo
  - arm
  - gimbtonomy
  - safety
  - science

test-enc-abs-pwm:
  - nucleo
  - arm
  - gimbtonomy
  - science

test-moisture:
  - nucleo
  - science

test-pid:
  - nucleo
  - arm
  - gimbtonomy
  - safety
  - science

test-pwm:
  - nucleo
  - arm
  - gimbtonomy
  - science

test-pwmin:
  - nucleo
  - arm
  - gimbtonomy
  - science

test-servo:
  - nucleo
  - arm
  - gimbtonomy
  - safety
  - science
